name: Build and Push Docker Image

on:
  push:
    branches:
      - main # atau sesuaikan dengan branch kamu, misal 'master' atau 'dev'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./App # <--- karena Dockerfile ada di App
          file: ./App/Dockerfile # <--- lokasi Dockerfile-nya
          push: true
          tags: johanpramudito/fastapi-backend:latest
